/**
 * CostGuardAI — Explanation Builder
 *
 * Deterministic, rule-based explanation generator.
 * No generative AI — output is fully determined by risk scoring inputs.
 *
 * buildExplanation() accepts the raw outputs of assessRisk() and returns
 * a structured Explanation block with stable, reproducible content.
 *
 * Dependency note: this module intentionally does NOT import from ./risk
 * to avoid a circular dependency (risk.ts → explanation-builder.ts → risk.ts).
 * Callers pass riskScore, riskLevel, and riskDrivers as primitive values.
 */

import { DRIVER_EXPLANATIONS, type Explanation } from "./explanations";

/** Minimal inline type — mirrors RiskDriver from risk.ts without importing it. */
interface RiskDriverRef {
  name: string;
  impact: number;
  fixes: string[];
}

/** Display labels for each risk level string. */
const RISK_BAND_LABELS: Record<string, string> = {
  safe: "Safe",
  low: "Low",
  warning: "Warning",
  high: "High",
  critical: "Critical",
};

/**
 * Build a deterministic Explanation from assessRisk() outputs.
 *
 * @param riskScore   - Integer 0–100 from assessRisk()
 * @param riskLevel   - "safe" | "low" | "warning" | "high" | "critical"
 * @param riskDrivers - Top-N drivers sorted by impact descending (from assessRisk)
 */
export function buildExplanation(
  riskScore: number,
  riskLevel: string,
  riskDrivers: RiskDriverRef[]
): Explanation {
  const band = RISK_BAND_LABELS[riskLevel] ?? riskLevel;

  // top_risk_drivers: names of drivers with non-trivial impact (> 5)
  // Order is preserved from riskDrivers (already impact-desc sorted).
  const top_risk_drivers = riskDrivers
    .filter((d) => d.impact > 5)
    .map((d) => d.name);

  // contributing_factors: static factors for each active driver, in driver priority order.
  // Deduplication preserves first-seen order — deterministic because riskDrivers order is stable.
  const seenFactors = new Set<string>();
  const contributing_factors: string[] = [];
  for (const driver of riskDrivers) {
    if (driver.impact <= 5) continue;
    const meta = DRIVER_EXPLANATIONS[driver.name];
    if (!meta) continue;
    for (const factor of meta.contributing_factors) {
      if (!seenFactors.has(factor)) {
        seenFactors.add(factor);
        contributing_factors.push(factor);
      }
    }
  }

  // mitigation_suggestions: dynamic (contextual) fixes from the engine first —
  // these are deterministically generated by the scoring heuristics.
  // Fallback to static base_mitigations if no dynamic fixes triggered.
  const seenMitigations = new Set<string>();
  const mitigation_suggestions: string[] = [];
  for (const driver of riskDrivers) {
    for (const fix of driver.fixes) {
      if (!seenMitigations.has(fix)) {
        seenMitigations.add(fix);
        mitigation_suggestions.push(fix);
      }
    }
  }

  if (mitigation_suggestions.length === 0 && riskDrivers.length > 0) {
    const meta = DRIVER_EXPLANATIONS[riskDrivers[0].name];
    if (meta) {
      for (const m of meta.base_mitigations.slice(0, 2)) {
        mitigation_suggestions.push(m);
      }
    }
  }

  // summary: one deterministic sentence encoding score, band, and top drivers.
  let summary: string;
  if (top_risk_drivers.length === 0) {
    summary = `CostGuardAI Safety Score: ${100 - riskScore} (${band}). No significant risk drivers detected.`;
  } else if (top_risk_drivers.length === 1) {
    summary = `CostGuardAI Safety Score: ${100 - riskScore} (${band}) driven primarily by ${top_risk_drivers[0]}.`;
  } else {
    summary = `CostGuardAI Safety Score: ${100 - riskScore} (${band}) driven primarily by ${top_risk_drivers[0]} and ${top_risk_drivers[1]}.`;
  }

  return {
    summary,
    top_risk_drivers,
    contributing_factors,
    mitigation_suggestions,
  };
}
